import { relations, sql } from "drizzle-orm";
import { bigint, boolean, index, integer, numeric, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const memberRole = pgEnum("member_role", ["owner", "manager", "inventory", "kitchen", "accountant", "viewer"]);
export const movementType = pgEnum("movement_type", ["purchase", "sale_consumption", "waste", "transfer_in", "transfer_out", "stock_count_adjustment", "return_to_supplier", "manual_adjustment"]);
export const wasteReason = pgEnum("waste_reason", ["expired", "damaged", "overproduction", "preparation_error", "quality_issue", "other"]);
export const purchaseStatus = pgEnum("purchase_status", ["draft", "received", "cancelled"]);

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };
export const organizations = pgTable("organizations", { id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull(), slug: text("slug").notNull(), currency: text("currency").notNull().default("TND"), locale: text("locale").notNull().default("fr-TN"), timezone: text("timezone").notNull().default("Africa/Tunis"), ...timestamps }, t => [uniqueIndex("organizations_slug_uidx").on(t.slug)]);
export const locations = pgTable("locations", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: text("name").notNull(), address: text("address"), isActive: boolean("is_active").notNull().default(true), ...timestamps }, t => [index("locations_org_idx").on(t.organizationId)]);
export const organizationMembers = pgTable("organization_members", { organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull(), role: memberRole("role").notNull().default("viewer"), defaultLocationId: uuid("default_location_id").references(() => locations.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => [primaryKey({ columns: [t.organizationId, t.userId] }), index("org_members_user_idx").on(t.userId)]);
export const units = pgTable("units", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }), code: text("code").notNull(), name: text("name").notNull(), dimension: text("dimension").notNull(), multiplierToBase: numeric("multiplier_to_base", { precision: 18, scale: 6 }).notNull().default("1"), isBase: boolean("is_base").notNull().default(false) }, t => [uniqueIndex("units_org_code_uidx").on(t.organizationId, t.code)]);
export const ingredients = pgTable("ingredients", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: text("name").notNull(), sku: text("sku"), baseUnitCode: text("base_unit_code").notNull(), minimumStock: numeric("minimum_stock", { precision: 18, scale: 3 }).notNull().default("0"), latestUnitCostMillis: integer("latest_unit_cost_millis").notNull().default(0), isActive: boolean("is_active").notNull().default(true), ...timestamps }, t => [index("ingredients_org_idx").on(t.organizationId), uniqueIndex("ingredients_org_name_uidx").on(t.organizationId, t.name)]);
export const suppliers = pgTable("suppliers", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: text("name").notNull(), phone: text("phone"), email: text("email"), notes: text("notes"), ...timestamps }, t => [index("suppliers_org_idx").on(t.organizationId)]);
export const supplierProducts = pgTable("supplier_products", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), supplierId: uuid("supplier_id").notNull().references(() => suppliers.id, { onDelete: "cascade" }), ingredientId: uuid("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "cascade" }), supplierSku: text("supplier_sku"), packQuantity: numeric("pack_quantity", { precision: 18, scale: 3 }).notNull().default("1"), lastPriceMillis: integer("last_price_millis").notNull().default(0), ...timestamps }, t => [index("supplier_products_org_idx").on(t.organizationId)]);
export const purchases = pgTable("purchases", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), locationId: uuid("location_id").notNull().references(() => locations.id, { onDelete: "cascade" }), supplierId: uuid("supplier_id").references(() => suppliers.id, { onDelete: "set null" }), invoiceNumber: text("invoice_number"), status: purchaseStatus("status").notNull().default("received"), totalMillis: integer("total_millis").notNull().default(0), receivedAt: timestamp("received_at", { withTimezone: true }).defaultNow().notNull(), createdBy: uuid("created_by"), clientOperationId: uuid("client_operation_id"), ...timestamps }, t => [index("purchases_org_location_idx").on(t.organizationId, t.locationId), uniqueIndex("purchases_client_operation_uidx").on(t.clientOperationId)]);
export const purchaseItems = pgTable("purchase_items", { id: uuid("id").primaryKey().defaultRandom(), purchaseId: uuid("purchase_id").notNull().references(() => purchases.id, { onDelete: "cascade" }), ingredientId: uuid("ingredient_id").notNull().references(() => ingredients.id), quantity: numeric("quantity", { precision: 18, scale: 3 }).notNull(), unitCostMillis: integer("unit_cost_millis").notNull(), lineTotalMillis: integer("line_total_millis").notNull() });
export const stockMovements = pgTable("stock_movements", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), locationId: uuid("location_id").notNull().references(() => locations.id, { onDelete: "cascade" }), ingredientId: uuid("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "cascade" }), type: movementType("type").notNull(), quantity: numeric("quantity", { precision: 18, scale: 3 }).notNull(), unitCostMillis: integer("unit_cost_millis").notNull().default(0), referenceType: text("reference_type"), referenceId: uuid("reference_id"), note: text("note"), performedBy: uuid("performed_by"), clientOperationId: uuid("client_operation_id"), occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => [index("stock_movements_lookup_idx").on(t.organizationId, t.locationId, t.ingredientId), uniqueIndex("stock_movements_client_operation_uidx").on(t.clientOperationId)]);
export const wasteEntries = pgTable("waste_entries", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), locationId: uuid("location_id").notNull().references(() => locations.id, { onDelete: "cascade" }), ingredientId: uuid("ingredient_id").notNull().references(() => ingredients.id), quantity: numeric("quantity", { precision: 18, scale: 3 }).notNull(), estimatedCostMillis: integer("estimated_cost_millis").notNull().default(0), reason: wasteReason("reason").notNull(), note: text("note"), createdBy: uuid("created_by"), clientOperationId: uuid("client_operation_id"), occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => [index("waste_entries_org_location_idx").on(t.organizationId, t.locationId), uniqueIndex("waste_entries_client_operation_uidx").on(t.clientOperationId)]);
export const recipes = pgTable("recipes", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: text("name").notNull(), yieldQuantity: numeric("yield_quantity", { precision: 18, scale: 3 }).notNull().default("1"), version: integer("version").notNull().default(1), isActive: boolean("is_active").notNull().default(true), ...timestamps }, t => [index("recipes_org_idx").on(t.organizationId)]);
export const recipeIngredients = pgTable("recipe_ingredients", { recipeId: uuid("recipe_id").notNull().references(() => recipes.id, { onDelete: "cascade" }), ingredientId: uuid("ingredient_id").notNull().references(() => ingredients.id), quantity: numeric("quantity", { precision: 18, scale: 4 }).notNull() }, t => [primaryKey({ columns: [t.recipeId, t.ingredientId] })]);
export const menuItems = pgTable("menu_items", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), recipeId: uuid("recipe_id").references(() => recipes.id, { onDelete: "set null" }), name: text("name").notNull(), sellingPriceMillis: integer("selling_price_millis").notNull(), packagingCostMillis: integer("packaging_cost_millis").notNull().default(0), isActive: boolean("is_active").notNull().default(true), ...timestamps }, t => [index("menu_items_org_idx").on(t.organizationId)]);
export const auditLogs = pgTable("audit_logs", { id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(), organizationId: uuid("organization_id").notNull(), userId: uuid("user_id"), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id"), metadata: text("metadata"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => [index("audit_logs_org_idx").on(t.organizationId)]);

export const organizationsRelations = relations(organizations, ({ many }) => ({ locations: many(locations), members: many(organizationMembers), ingredients: many(ingredients) }));
export const ingredientsRelations = relations(ingredients, ({ one, many }) => ({ organization: one(organizations, { fields: [ingredients.organizationId], references: [organizations.id] }), movements: many(stockMovements) }));

export const inventoryBalanceSql = sql`coalesce(sum(${stockMovements.quantity}), 0)`;
